
//import java.awt.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFileChooser;
import javax.swing.JTextField;

/**
 *
 * @author izem
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
    }

    private static final String  SEPERATOR="-"; // TE3 LA FONCTION Find_it ,fais pas attention.
    //Resultat result= new Resultat();
    Error error = new Error();
    ErrorGrande error_grande = new ErrorGrande();
    FormatError format_error = new FormatError();

    private void Find_it(String fileName, JTextField field) {
        // TODO Auto-generated method stub
        File file = new File(fileName);
        //get the readers ready
        FileInputStream inputFile = null;
        StringBuilder textInput= new StringBuilder();
        String line=null;
        String[] khat = null;



        if(fileName.contains(".txt")== false){
            error.setVisible(true);
            error.setDefaultCloseOperation(Error.DISPOSE_ON_CLOSE);
        }

        else{

            try {

                inputFile = new FileInputStream(file);
                BufferedReader reader = new BufferedReader(new InputStreamReader(inputFile));

                //read the file line by line and append the separator
                while ((line= reader.readLine())!=null){
                    textInput.append(line+SEPERATOR);
                }
                reader.close();
                inputFile.close();

                String[] lines   = textInput.toString().split(SEPERATOR);
                int flag= 0;

                for (int i= lines.length-1 ; i > -1 ; --i){
                    line = lines[i];
                    khat = lines[i].split(" ", 3);
                    //System.out.println(lines[i]+"\n");
                    if(line.contains("#=GC SS_cons")==true){
                        field.setText(khat[2].strip());// je met strip pour enlever les espaces te3 le fichiers li 9ble les (- (voir test.txt).
                        flag+=1; // j'ai trouvé le SS_cons , tsema on est bon.
                        break;
                    }
                    if(flag==0){
                        // hna ça veut dire que j'ai pas trouve le SS_CONSS !!
                        error_grande.setVisible(true);
                        error_grande.setDefaultCloseOperation(ErrorGrande.DISPOSE_ON_CLOSE);
                        // tu mets ze3ma , votre fichier est certes .txt mais je ne retrouve pas la structure secondaire SS_CONSS !
                    }

                }
            } catch (FileNotFoundException e) {
                System.out.println("The file with name ="+file.getName()+" could not be found");
                e.printStackTrace();
            } catch (IOException e) {
                System.out.println("There has been a IO exception");
                e.printStackTrace();
            }
        }
    } // finalement pas besoin de lire le fichier à l'envers mais kheliha kesh nehar elle vas servir.


    private  String Trad(String seq){ // j'aurais pu utiliser la boucle switch mais bon c'est mieux haka
        char[] letter =seq.toCharArray();
        String final_seq= null;
        for(int i =0 ; i< letter.length;i++){
            if(letter[i]==','||letter[i]=='_'||letter[i]==':'||letter[i]=='-'){
                letter[i]='.';
            }
            else if(letter[i]=='{'||letter[i]=='['||letter[i]=='<'){
                letter[i]='(';
            }
            else if(letter[i]=='}'||letter[i]==']'||letter[i]=='>'){
                letter[i]=')';
            }
        }
        return (final_seq.valueOf(letter)) ;  // a la fin ne3wed nradou String.

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setResizable(false);
        setSize(new java.awt.Dimension(1168, 550));

        jPanel2.setBackground(java.awt.Color.gray);
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(169, 110, 195), 3, true));

        jPanel1.setBackground(java.awt.Color.pink);

        jLabel1.setFont(new java.awt.Font("L M Roman Demi10", 0, 24)); // NOI18N
        jLabel1.setText("RNA comparator ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(37, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(155, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(430, 430, 430))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(java.awt.Color.gray);

        jTextField2.setBackground(java.awt.Color.white);
        jTextField2.setText("Seq 1 ");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setBackground(java.awt.Color.white);
        jTextField3.setText("Seq 2");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(java.awt.Color.lightGray);
        jButton4.setForeground(java.awt.Color.lightGray);
        jButton4.setIcon(new javax.swing.ImageIcon("/home/izem/Pictures/iconfinder_filetype_-_substract_3440894.png")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(java.awt.Color.lightGray);
        jButton5.setForeground(java.awt.Color.lightGray);
        jButton5.setIcon(new javax.swing.ImageIcon("/home/izem/Pictures/iconfinder_filetype_-_substract_3440894.png")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setBackground(java.awt.Color.darkGray);
        jButton1.setForeground(java.awt.Color.green);
        jButton1.setText("Compare it baby !!!  ");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(26, 88, 221), 2, true));
        jButton1.setOpaque(true);
        jButton1.setRequestFocusEnabled(false);
        jButton1.setRolloverEnabled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(java.awt.Color.gray);
        jLabel2.setIcon(new javax.swing.ImageIcon("/home/izem/Pictures/yesrna.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(121, 121, 121)
                                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(41, 41, 41)
                                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(344, 344, 344)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(210, 210, 210)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jTextField3)
                                                                .addComponent(jTextField2))
                                                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(43, 43, 43)
                                                .addComponent(jButton1))
                                        .addComponent(jLabel2))
                                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon("/home/izem/Pictures/saclak (3).png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(3, 3, 3)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (jTextField3.getText().matches("[^A-Za-z0-9]+") && jTextField2.getText().matches("[^A-Za-z0-9]+")){ // quand les deux ne contiennent que des caractéres spéciaux (tsema aucun des 2 textfield ne contient de lettre,c'est juste pour m'assur que y'a pas de lettre
            if(jTextField3.getText().contains("<") && jTextField2.getText().contains("<")){ // je check un intrus stokolhm , ça devrait suffire on est pas la pour jouer à cache chache !!
                Trad(jTextField3.getText()); // hna je montre que j'ai traduit mon stocko en (- , mais c'est pas la peine.
                Trad(jTextField2.getText());
                //donc hna puisque j'ai vu qu'ils sont s/f stocko donc je les traduit et j'appelle jiaying
            }else{
                //si ils sont déja format (- donc c'est bon nbda ncompari. on appelle donc les méthodes te3 jiaying.
            }
        }

        else{
            error.setVisible(true);  // tu affiche un message comme quoi c'est format incorrect !!
            error.setDefaultCloseOperation(Error.DISPOSE_ON_CLOSE);
        }
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser chooser1 = new JFileChooser();
        int var = chooser1.showOpenDialog(null);
        //File file = chooser1.getSelectedFile();
        //String file_content = file.getAbsolutePath();
        //jTextField2.setText(file_content);
        if(var ==0 ){
            Find_it(chooser1.getSelectedFile().getAbsolutePath(),jTextField2);
        }
    }

    public void readFile(String filepath,JTextField field){
        BufferedReader reader;
        FileReader in;
        String ligne;
        String[] array;
        if(filepath.contains(".txt")== false){
            error.setVisible(true);
            error.setDefaultCloseOperation(error.DISPOSE_ON_CLOSE);
        }
        else{ // tsema uniquement si le fichier contient .txt ltemak je vais faire le read file et le mettre dans le texteField.
            try{
                in = new FileReader(new File(filepath));
                reader= new BufferedReader(in);

                ligne= reader.readLine();
                int flag= 0;
                do{
                    if(ligne.contains("#=GC SS_cons") == true){
                        array = ligne.split(" ", 3); // 9assem 3la l'espace besah tu laisse 3 element berk !
                        field.setText(array[2].strip());
                        break;
                    }
                } while(ligne != null);

            }catch (FileNotFoundException ex ){
                Logger.getLogger(Window.class.getName());

            } catch (IOException ex) {
                Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
            }


        }

    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser chooser2 = new JFileChooser();
        int var = chooser2.showOpenDialog(null);
        //File file = chooser2.getSelectedFile();
        //String filename = file.getAbsolutePath();
        if(var == 0 ){
            Find_it(chooser2.getSelectedFile().getAbsolutePath(),jTextField3);
        }


    }

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration
}
